-- 결제 테이블
create table if not exists p_payments
(
    id                         uuid         not null    primary key,
    user_id                    uuid         not null,
    funding_id                 uuid         not null,
    project_id                 uuid         not null,
    amount                     bigint       not null,
    status                     varchar(255) not null,
    pg_method                  varchar(20),
    pg_payment_key             varchar(100),
    pg_order_id                varchar(255),
    refund_account_bank        varchar(20),
    refund_account_number      varchar(50),
    refund_account_holder_name varchar(20),
    refund_reason              varchar(255),
    approved_at                timestamp(6),
    failed_at                  timestamp(6),
    refunded_at                timestamp(6),
    created_at                 timestamp(6),
    created_by                 uuid,
    updated_at                 timestamp(6),
    updated_by                 uuid,
    deleted_at                 timestamp(6),
    deleted_by                 uuid
);

-- 결제 상태 로그 테이블
create table p_payment_status_logs
(
    id          uuid         not null   primary key,
    payment_id  uuid         not null,
    prev_status varchar(255) not null,
    curr_status varchar(255) not null,
    reason      varchar(500),
    amount      bigint       not null,
    created_at  timestamp(6),
    created_by  uuid
);

-- 정산 테이블
create table p_settlements
(
    id                  uuid         not null   primary key,
    project_id          uuid         not null,
    total_amount        bigint       not null,
    service_fee         bigint       not null,
    pg_fee              bigint       not null,
    net_amount          bigint       not null,
    account_bank        varchar(255),
    account_number      varchar(255),
    account_holder_name varchar(255),
    status              varchar(255) not null,
    requested_at        timestamp(6),
    completed_at        timestamp(6),
    failed_at           timestamp(6),
    created_at          timestamp(6),
    created_by          uuid,
    deleted_at          timestamp(6),
    deleted_by          uuid,
    updated_at          timestamp(6),
    updated_by          uuid
);

-- 정산 상태 로그 테이블
create table p_settlement_status_logs
(
    id            uuid         not null primary key,
    settlement_id uuid         not null,
    prev_status   varchar(255) not null,
    curr_status   varchar(255) not null,
    reason        varchar(500),
    amount        bigint       not null,
    created_at    timestamp(6),
    created_by    uuid
);

-- 환불 Job 테이블
create table p_refund_jobs
(
    id          bigint generated by default as identity primary key,
    payment_id  uuid         not null   unique,
    project_id  uuid         not null,
    status      varchar(255) not null,
    retry_count integer      not null,
    reason      varchar(255),
    created_at  timestamp(6) not null,
    updated_at  timestamp(6) not null
);

-- Comments
comment on table p_payments is '결제 테이블';
comment on table p_payment_status_logs is '결제 상태 로그 테이블';
comment on table p_settlements is '정산 테이블';
comment on table p_settlement_status_logs is '정산 상태 로그 테이블';
comment on table p_refund_jobs is '환불 Job 테이블';

comment on column p_payments.status is '결제 상태 (PENDING, COMPLETED, FAILED, REFUNDED)';
comment on column p_settlements.status is '정산 상태 (PROCESSING, COMPLETED, FAILED)';
comment on column p_refund_jobs.status is '환불 Job 상태 (PENDING, IN_PROGRESS, COMPLETED, FAILED)';