package com.nowayback.project.domain.outbox.vo;

public enum EventType {
    PROJECT_DRAFT_SUBMITTED,

    PROJECT_REWARD_CREATION,
    PROJECT_FUNDING_CREATION,

    REWARD_CREATED,
    REWARD_CREATION_FAILED,
    REWARD_CREATION_COMPENSATION,

    FUNDING_CREATED,
    FUNDING_CREATION_FAILED,

    PROJECT_ACTIVATED,
    PROJECT_CREATION_FAILED;
}
